### PR TITLE
bugfix: added error handling.

### LINKED ISSUE #86: rpc: improve error handling
Improve error handling in the Unix socket

For now, we have the following code

```
    socket.listen((event) {
      LogManager.getInstance.debug('Event received is ${utf8.decode(event)}');
      completer.complete(utf8.decode(event));
    },
        onDone: () => LogManager.getInstance.debug('End JSON RPC Stream'),
        onError: (err) => LogManager.getInstance.error(err));
```

We should throw an exception is any error happens inside the `onError`

### PR DESCRIPTION
**Pull request by swaptr**
fixes #86

### CODE REVIEW

File: packages/rpc/lib/src/utils/exception/ln_client_error.dart [hunk 1]
```diff
@@ -0,0 +1,5 @@
+class LNClientException implements Exception {
+  String cause;
+
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/exception/ln_client_error.dart:3]:
```suggestion
  String cause;
  String code;
```

would be better also return the error code

File: packages/rpc/lib/src/utils/unix_rpc_client.dart [hunk 2]
```diff
@@ -17,12 +18,17 @@ class UnixRPCClient extends ServerProxyBase {
...
+    socket.listen(
+        (event) {
+          LogManager.getInstance
+              .debug('Event received is ${utf8.decode(event)}');
+          completer.complete(utf8.decode(event));
+        },
         onDone: () => LogManager.getInstance.debug('End JSON RPC Stream'),
-        onError: (err) => LogManager.getInstance.error(err));
+        onError: (err) {
+          LogManager.getInstance.error(err);
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/unix_rpc_client.dart:29]:
```suggestion
          LogManager.getInstance.error(err);
```

This should be a json map, with the following form

{ 
   "error": { 
          "message": "",
          "code": "",
          "data": ""
     }

as defined in https://www.jsonrpc.org/specification#error_object
}

We can make a better exception, by adding error code and data also inside the class

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Some comments, and also this need to be tested!

Try to pay invoices without channels!

File: packages/rpc/lib/src/utils/exception/ln_client_error.dart [hunk 3]
```diff
@@ -0,0 +1,7 @@
+class LNClientException implements Exception {
+  String message;
+  String code;
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/exception/ln_client_error.dart:3]:
```suggestion
  int code;
```

File: packages/rpc/lib/src/utils/unix_rpc_client.dart [hunk 4]
```diff
@@ -2,6 +2,7 @@ import 'dart:async';
 import 'dart:convert';
 import 'dart:io';
 
+import 'package:clightning_rpc/src/utils/exception/ln_client_error.dart';
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/unix_rpc_client.dart:5]: we should expose this exception in the file that it is outside the src this!

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

File: packages/rpc/test/clightning_rpc_test.dart [hunk 5]
```diff
@@ -43,5 +43,26 @@ void main() {
...
+      expect(client, isNotNull);
+      var params = <String, dynamic>{};
+      params['msatoshi'] = '100000msat';
+      params['label'] = 'from-dart';
+      params['description'] = 'This is a unit test';
+
+      var response = await client.simpleCall('invoice', params: params);
+      params = <String, dynamic>{};
+      params['bolt11'] = response["bolt11"];
+      await client.simpleCall('pay', params: params);
```
Comment (vincenzopalazzo) [inline packages/rpc/test/clightning_rpc_test.dart:59]: if this test pass without any error this means that there is some mistake around,  we should have an exception

File: packages/rpc/lib/src/utils/unix_rpc_client.dart [hunk 6]
```diff
@@ -17,12 +18,18 @@ class UnixRPCClient extends ServerProxyBase {
...
+              .debug('Event received is ${utf8.decode(event)}');
+          completer.complete(utf8.decode(event));
+        },
         onDone: () => LogManager.getInstance.debug('End JSON RPC Stream'),
-        onError: (err) => LogManager.getInstance.error(err));
+        onError: (error) {
+          LogManager.getInstance.error(error);
+          throw LNClientException(
+              error["code"], error["message"], error["data"]);
+        });
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/unix_rpc_client.dart:32]: Ok this is my mistake! the onError callback is trigger for other reason  maybe related to the stream.

In the CI i noted that there is the following error

```
cln_1       | ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cln_1       | │ #0   LogManager.info (package:cln_common/src/logger/logger_manager.dart:24:13)
cln_1       | │ #1   RPCClient.connect (package:clightning_rpc/src/clightning_rpc.dart:10:10)
cln_1       | ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
cln_1       | │ 💡 Connection to JSON RPC 2.0 at the following path /workdir/lightning_dir_one/regtest/lightning-rpc
cln_1       | └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cln_1       | ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cln_1       | │ #0   LogManager.debug (package:cln_common/src/logger/logger_manager.dart:16:13)
cln_1       | │ #1   UnixRPCClient.transmit.<anonymous closure> (package:clightning_rpc/src/utils/unix_rpc_client.dart:21:30)
cln_1       | ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
cln_1       | │ 🐛 Event received is {"jsonrpc":"2.0","result":{"foo_opt":"hello"},"id":791291083}
cln_1       | │ 🐛 
cln_1       | │ 🐛 
cln_1       | └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

And I think we need the fix looks like this (please do no apply I do not test the code in the local so I do not know if this is correct dart)

```dart
 socket.listen(
        (event) {
          LogManager.getInstance
              .debug('Event received is ${utf8.decode(event)}');
         if (event.containsKey("errors")) {
              var error = event["errors"];
            var error = LNClientException(
              error["code"], error["message"], error["data"]);
            completer.completeException(error);
           return;
         }
          completer.complete(utf8.decode(event));
        },
        onDone: () => LogManager.getInstance.debug('End JSON RPC Stream'),
        onError: (error) {
          LogManager.getInstance.error(error);
          completer.completeException(error);
        });
```

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

File: packages/rpc/lib/src/utils/unix_rpc_client.dart [hunk 7]
```diff
@@ -17,12 +18,23 @@ class UnixRPCClient extends ServerProxyBase {
...
-      completer.complete(utf8.decode(event));
-    },
+    socket.listen(
+        (event) {
+          LogManager.getInstance
+              .debug('Event received is ${utf8.decode(event)}');
+          Map<String, dynamic> eventMap = jsonDecode(utf8.decode(event));
+          if (eventMap.containsKey("error")) {
+            var error = eventMap["error"];
+            error = LNClientException(
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/unix_rpc_client.dart:28]:
```suggestion
            var exception = LNClientException(
```

please keep python away :D

File: packages/rpc/test/clightning_rpc_test.dart (hunk 5 above)
Comment (vincenzopalazzo) [inline packages/rpc/test/clightning_rpc_test.dart:59]:
```suggestion
     
      expect(() async =>  await client.simpleCall('pay', params: params), throwsA(TypeMatcher<LNClientException>()));
```

Comment (vincenzopalazzo) [reply packages/rpc/test/clightning_rpc_test.dart:59]: I'm always worried when the test is green on the first run, which means the test is fake.

Let's fail and keep your eyes on the log failure!

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

**Comment by vincenzopalazzo** [comment]
I'm not able to find the log regarding the rpc package I think it is skipped in some way!

It is better make a double check if the CI is checking all the package

**Comment by vincenzopalazzo** [comment]
Prooved https://github.com/dart-lightning/lndart.cln/pull/92/commits/0be832d006d6e3face2101daac556c35119e6e5d

File: packages/rpc/lib/src/utils/unix_rpc_client.dart [hunk 8]
```diff
@@ -17,12 +18,23 @@ class UnixRPCClient extends ServerProxyBase {
...
+        (event) {
+          LogManager.getInstance
+              .debug('Event received is ${utf8.decode(event)}');
+          Map<String, dynamic> eventMap = jsonDecode(utf8.decode(event));
+          if (eventMap.containsKey("error")) {
+            var error = eventMap["error"];
+            var exception = LNClientException(
+                error["code"], error["message"], error["data"]);
+            completer.completeError(exception);
+          }
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/unix_rpc_client.dart:31]:
```suggestion
          if (eventMap.containsKey("error")) {
            var error = eventMap["error"];
            var exception = LNClientException(
                error["code"], error["message"], error["data"]);
            completer.completeError(exception);
          } else {
               completer.complete(utf8.decode(event));
          }
```

This solve the timeout in the CI, you forgot to return in case of success

**Review by vincenzopalazzo — DISMISSED** [review]

File: packages/rpc/lib/src/utils/unix_rpc_client.dart [hunk 9]
```diff
@@ -29,7 +29,7 @@ class UnixRPCClient extends ServerProxyBase {
                 error["code"], error["message"], error["data"]);
             completer.completeError(exception);
           } else {
-            completer.complete(utf8.decode(event));
+            completer.complete(utf8.decode(event).toString());
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/unix_rpc_client.dart:32]:
```suggestion
            completer.complete(utf8.decode(event));
```

Why it is the same as before, why do we need a `toString()`?

File: packages/rpc/lib/src/utils/exception/ln_client_error.dart [hunk 10]
```diff
@@ -0,0 +1,7 @@
+class LNClientException implements Exception {
+  String message;
+  int code;
+  String data;
```
Comment (vincenzopalazzo) [inline packages/rpc/lib/src/utils/exception/ln_client_error.dart:4]:
```suggestion
  String? data;
```

This can be null, from spec
```
data
A Primitive or Structured value that contains additional information about the error.
This may be omitted.
The value of this member is defined by the Server (e.g. detailed error information, nested errors etc.).
```

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

**Review by vincenzopalazzo — APPROVED** [review]
